FROM date_parser_ubi9_5_base:latest




# Add a non-root user
RUN groupadd -r appuser && useradd -r -g appuser appuser

RUN mkdir date_parser
WORKDIR /date_parser
ADD . /date_parser

RUN /my_venv/bin/python3.11 compiler.py build_ext --inplace 


# Change ownership of the directory to the non-root user
RUN chown -R appuser:appuser /date_parser

# Switch to the non-root user
USER appuser


CMD [ "/my_venv/bin/python3.11", "-m", "gunicorn", "app:app", "-b", "0.0.0.0:8035", "-k" ,"gevent", "-w", "5", "--timeout", "5000", "--graceful-timeout", "4890" ]